### ISSUE TITLE
what do you mean'scenes'

### ISSUE THREAD

**Issue by elenalucixian** [KonVas/Greap#1]

**Comment by elenalucixian** [comment]
Do you mean put the name of the sound file into the Greap.scd? however didn't find ~sounds[\nameOf Sound]in this file. Thank you!

**Comment by KonVas** [comment]
Assuming you followed these steps:

- Move Beerffers.SuperCollider + Subduct classes to Extensions folder of SuperCollider found in Application Support folder. This is a vital step in order to make SuperCollider go beep.
- Place any sound files (mono) you want to use at the folder inside GreapCode folder Greap/GreapCode/Sounds.
- Open Greap.scd in SuperCollider and execute the whole file (this should open GECO and run the GECOMapper file automatically).
- If you have placed the sounds you want to use in Greap/GreapCode/Sounds folder go to 'scenes' and type the name of the sound to use: ~sounds[\nameOfSound] this will be the name of the sound that this scene will manipulate. The name of the sound must be typed exactly as the one in the folder without the extension e.g., \thisSound and not \thisSound.wav failing to do so the sound will be inaccessible, and most likely this will be the reason that SuperCollider remain silent.

Then you must create a folder named Sounds in the root folder that is Greap. Once you do that, you can type the name of the file in each scene by editing this bit:

`~sounds[\addNameOfSound]`

You need to type one of the name of the audio files as it is in the Sounds folder e.g. `~sounds[\bell]` this way you can assign different sound files for processing.

I admit this is a bit confusing, but easy to solve. Please let me know if this helps.
